const FETCH_ALL_DOCKER_CONTAINER_DATA = 'FETCH_ALL_DOCKER_CONTAINER_DATA';
const FIND_CONTAINER_BY_SEARCH_TEXT = 'FIND_CONTAINER_BY_SEARCH_TEXT';
const UPDATE_THE_CONTAINER_STATUS = 'UPDATE_THE_CONTAINER_STATUS';
const CANCEL_THE_SEARCH_MODE = 'CANCEL_THE_SEARCH_MODE';
const DELETE_THE_CONTAINER = 'DELETE_THE_CONTAINER';

export {
    FETCH_ALL_DOCKER_CONTAINER_DATA,
    FIND_CONTAINER_BY_SEARCH_TEXT,
    UPDATE_THE_CONTAINER_STATUS,
    CANCEL_THE_SEARCH_MODE,
    DELETE_THE_CONTAINER,
}
