const FETCH_ALL_DOCKER_CONTAINER_DATA = 'FETCH_ALL_DOCKER_CONTAINER_DATA';
const FIND_CONTAINER_BY_SEARCH_TEXT = 'FIND_CONTAINER_BY_SEARCH_TEXT';

export {
    FETCH_ALL_DOCKER_CONTAINER_DATA,
    FIND_CONTAINER_BY_SEARCH_TEXT,
}
